### ISSUE TITLE
<initializer_list>

### ISSUE THREAD

**Issue by tdkpipo96** [lsaavedr/XBeeNG#1]
al cargar la libreria aparece un error de que el archivo initializer_list no se encuentra su directorio
como puedo solucionar esto o donde encuentro o descargo ese archivo 
gracias

**Comment by lsaavedr** [comment]
No pude reproducir el error, quizás si me explicas con un poco más de detalle: sistema operativo, versión del IDE de arduino, y cómo estás "cargando" la librería puedo ver qué pasa... ojo que debes incluir la cabecera `#include <XBeeNG.h>` al principio de tu sketch y no se necesita ningún archivo con el nombre "initializer_list"

**Comment by tdkpipo96** [comment]
Si, yo cargo la librería de manera normal 
Pero inmediatamente compilo el sketch me aparece como error que no se encontro el directorio initializer_list 
El IDE de Arduino es 1.8.5 y mi sistema operativo es Windows 7 
Y te reitero de nuevo el compilador  pide ese archivo initializer_list no se porque ojalá me puedas ayudar

**Comment by lsaavedr** [comment]
Acá encontré un archivo con ese nombre: 

https://github.com/Trefex/arduino-airquality/blob/master/aq6s/StandardCpp/initializer_list

Pero si te fijas bien ese archivo corresponde a las "cabeceras" oficiales del compilador GCC, por lo tanto tu problema está en la instalación de Arduino, lamentablemente no utilizo Windows, pero lo poco y nada que recuerdo es que tienes que revisar tus variables de entorno (el $PATH y esas cosas), o deberías intentar instalando todo desde 0.

Por otra parte... no será que utilizas otra librería que necesita esas cabeceras?, esta librería no las necesita...

**Comment by tdkpipo96** [comment]
gracias, voy a probar a ver que tal
