### ISSUE TITLE
ejemplos 

### ISSUE THREAD

**Issue by tdkpipo96** [lsaavedr/XBeeNG#2]
buenas noches 

ya pude cargar la libreria pero el xbee pareciera que no tuviera activados los pines rx tx
no se si sea por cosas de detalles en codigo o algo asi 
quizas uestedes no tienen ejemplos hechos ademas de los que estan 
ahi??
depronto uds no saben que consideracion se debe tener con los Xbee pro 900 HP?

**Comment by lsaavedr** [comment]
Las principales consideraciones que debes tener son eléctricas, siempre revisa que cumplas con lo indicado en la tabla "Table 3: Electrical Specifications for GPIO Pins" del manual (pag. ±16), además personalmente te recomendaría hacer las conexiones a RX y TX con resistencias no menores a 40homs (enntre 47homs a 100homs está bien) ya que si te equivocas y conectas al revés van a "chocar" las salidas, y aunque te parezca que es muy tonto conectar mal, con el tiempo te vas a dar cuenta que esto pasa tan seguido que es más tonto no poner estas resistencias.

Cumpliendo lo anterior, que es lo más importante, lo segundo más importante es conseguir un "gateway" que cumpla lo anterior, y vuelvo a recalcar que cumpla lo anterior porque estos módulos son un poco frágiles eléctricamente, admiten voltages entre 2.1v a 3.6v (por ejemplo) y la mayoría de los gateway tienen salidas de 5v.

Si todo eso está ok, lo último es probar con distintas "baud rates", un comando simple, el más simple (esto mismo se hace para casi todos los módulos que se conectan al puerto serial), si luego de enviar el comando y esperar un tiempo suficiente recibes una respuesta válida has encontrado el "baud rate" del módulo...
