### ISSUE TITLE
Imprimir y almacenar solo el payload

### ISSUE THREAD

**Issue by tdkpipo96** [lsaavedr/XBeeNG#3]
Buenas tardes 
Cuando se adquiere un dato, hay alguna manera de adquirir solo el payload
almacenarlo e imprimirlo  ? Es que en el ejemplo
Se imprime todo el frame

**Comment by tdkpipo96** [comment]
Buenas tardes 
Cuando se adquiere un dato, ¿hay alguna manera de adquirir solo el payload 
almacenado e imprimirlo? Es que en el ejemplo 
Se imprime todo el marco

**Comment by lsaavedr** [comment]
debes castear a la clase correcta y luego utilizar la API para obtener lo que quieras, puedes mostrar tu ejemplo? así es más fácil indicarte con algo concreto en lugar de algo abstracto...

**Comment by tdkpipo96** [comment]
mira lo que pasa es que cuando adquiero un dato con la arduino 
el monitor serie imprime lo siguiente 

"cmdID: 90 Address64Msb: 00 13 A2 00 Address64Lsb: 41 54 63 B4 Address16: FF FE Options: C1 Data: 6D 65 6D 65"

entonces yo quisiera saber si es posible solo imprimir la parte que dice Data: 6D 65 6D 65 y ademas de eso almacenar esa porción del dato en una variable.

**Comment by lsaavedr** [comment]
si se puede, pero puedes colocar tu código? es más fácil indicarte...

se supone que el largo y el dato lo puedes obtener con `getCmdDataLength` y `getCmdData` respectivamente... pero depende de la clase o subclase que estás utilizando...

**Comment by tdkpipo96** [comment]
esto es lo que tengo hasta el momento
`
//#include <SoftwareSerial.h>
#include <XBeeNG.h>




XBee xbng = XBee ();

//SoftwareSerial Serialob(8, 9); //RX,TX
void setup() {
  Serial.begin(9600);
  
  //Serialob.begin(9600);
  xbng.begin(Serial);
}

void loop() {
 
  // Sending { 0xDA, 0x7A } to address64: 0x0013A200 0x403E0F30
  /*
  TxRequest txReq = TxRequest(2, 0x0013A200, 0x415463B4, { 0x41, 0x4E, 0x44, 0x52, 0x45, 0x53 } );
  xbng.send(txReq);
  delay(1000);
  */


  xbng.readPacket(); // Removing old data for consuming new data
  xbng.readPacketUntilAvailable(); // Force read a new valid data
  
  // Getting data to print a summary
  
  XBeeApiFrame* xbApiFrame = &xbng.getApiFrame();
  xbApiFrame->printSummary(Serial);
 
}
`

**Comment by tdkpipo96** [comment]
esto es lo que tengo hasta el momento solo esstoy adquiriendo datos 

//#include <SoftwareSerial.h>
#include <XBeeNG.h>




XBee xbng = XBee ();

//SoftwareSerial Serialob(8, 9); //RX,TX
void setup() {
  Serial.begin(9600);
  xbng.begin(Serial);
}

void loop() {

  xbng.readPacket(); // Removing old data for consuming new data
  xbng.readPacketUntilAvailable(); // Force read a new valid data
  
  // Getting data to print a summary
  
  XBeeApiFrame* xbApiFrame = &xbng.getApiFrame();
  xbApiFrame->printSummary(Serial);
 
}

**Comment by lsaavedr** [comment]
Lo primero que debes hacer es tener dos puertos seriales (no es necesario pero sí hace todo mucho más cómodo al principio), un puerto serial (que no es necesario) es el que conecta tu PC y el MCU, que puede servir para imprimir los datos o leer comandos que ingreses (debug), y el otro puerto serial (que sí es necesario) es el que conecta el XBee y el MCU. Si utilizas el mismo puerto para las fos cosas, van a pasar cosas extrañas como que al leer un dato al mismo tiempo esté procesando el dato que el mismo xbee está escribiendo...

**Comment by tdkpipo96** [comment]
listo ok enseguida agrego otro puerto con SoftwareSerial
por otro lado como entonces adquiero y almaceno solo la parte del payload 
e estado provando con getCmdDataLength y getCmdData como dijiste pero solo me arroja un cero 
no se si lo estoy haciendo mal o que ?
en el codigo que tengo como puedo entonces hacer eso

**Comment by lsaavedr** [comment]
Debes hacer esto cuando tengas los dos puertos seriales (con pines distintos) funcionando:

`if (xbApiFrame->getCmdId() == RX_RESPONSE) {

        RxResponse* pt = static_cast<RxResponse*>(xbApiFrame);

        uint8_t* data = pt->getData();

        uint16_t dataLength = pt->getDataLength();

    }
` 

La idea es que dependiendo del tipo derespuesta, esta la casteas al tipo adecuado y obtienes los campos que necesitas.

**Comment by tdkpipo96** [comment]
ya puse el otro serial 
aunque aqui me aprecian dos errores
XBeeApiFrame->getCmdId() == RX_RESPONSE
en primera instancia el primer error se soluciono cambiando xbApiFrame por  XBeeApiFrame
y el segundo, me señala el ide de arduino que es por el simbolo ->
ahi que puedo hacer?

**Comment by tdkpipo96** [comment]
.

**Comment by lsaavedr** [comment]
Yo compilo sin problemas el siguiente código, ojo que `Serial != Serial1`:

```cpp
#include <XBeeNG.h>

XBee xbng = XBee ();

void setup() {
  Serial.begin(9600);
  xbng.begin(Serial1);
}

void loop() {

  xbng.readPacket();
  xbng.readPacketUntilAvailable();

  XBeeApiFrame* xbApiFrame = &xbng.getApiFrame();
  if (xbApiFrame->getCmdId() == RX_RESPONSE) {

        RxResponse* pt = static_cast<RxResponse*>(xbApiFrame);

        uint8_t* data = pt->getData();
        uint16_t dataLength = pt->getDataLength();

  }
}
```

**Comment by tdkpipo96** [comment]
listo ya estoy usando puerto seriales diferentes 
y al adquirir e imprimir el tamaño del dato da un valor  4 lo cual es correcto  ya que el dato que envió en hexadecimal hacia el xbee es "6D 65 6D 65" pero al imprimir el payload me arroja un valor de 596 
no se si sea un dato erróneo o sea algo del formato de los números 

estoy imprimiendo asi 

  XBeeApiFrame* xbApiFrame = &xbng.getApiFrame();
  if (xbApiFrame->getCmdId() == RX_RESPONSE) {

    RxResponse* pt = static_cast<RxResponse*>(xbApiFrame);

    uint8_t* data = pt->getData();
    dataaux= data;
    uint16_t dataLength = pt->getDataLength();
    dataaux1=dataLength;
  

  }
  Serial.println(dataaux);
  Serial.println(dataaux1);
